package com.github.danzx.xof.dataprovider.jpa.adapter.mapper

import com.github.danzx.xof.core.domain.Post
import com.github.danzx.xof.core.domain.SimpleUser
import com.github.danzx.xof.dataprovider.jpa.entity.PostJpaEntity
import com.github.danzx.xof.dataprovider.jpa.entity.UserJpaEntity

fun Post.toPostJpaEntity(user: UserJpaEntity) = PostJpaEntity(
    id = id.orAutoGeneratedId(),
    title = title,
    content = content,
    created = created,
    updated = updated,
    user = user
)

fun PostJpaEntity.toPost(votes: Long) = Post(
    id = id!!,
    title = title,
    content = content,
    created = created,
    updated = updated,
    votes = votes,
    user = SimpleUser(
        id = user.id!!,
        username = user.username
    )
)
