package com.github.danzx.xof.dataprovider.jpa.adapter.mapper

import com.github.danzx.xof.core.domain.User
import com.github.danzx.xof.core.domain.orAutoGeneratedId
import com.github.danzx.xof.dataprovider.jpa.entity.UserJpaEntity

fun User.toUserJpaEntity() = UserJpaEntity(
    id.orAutoGeneratedId(),
    name,
    lastName,
    username,
    avatarImageUrl,
    join
)

fun UserJpaEntity.toUser() = User(
    id!!,
    name,
    lastName,
    username,
    avatarImageUrl,
    join
)